# Generated by Django 5.1.3 on 2024-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(default='Custumer', max_length=8),
        ),
    ]
