# Generated by Django 5.1.3 on 2025-01-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
